# Generated by Django 5.2.1 on 2025-06-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0002_commentary_created_at_publication_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentary",
            name="likes_count",
            field=models.IntegerField(default=0, verbose_name="количество лайков"),
        ),
        migrations.AlterField(
            model_name="publication",
            name="likes_count",
            field=models.IntegerField(default=0, verbose_name="количество лайков"),
        ),
        migrations.AlterField(
            model_name="publication",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="количество просмотров"),
        ),
    ]
