# Generated by Django 5.2.1 on 2025-06-01 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0004_alter_publication_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commentary",
            name="likes_count",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="likes_count",
        ),
        migrations.AddField(
            model_name="commentary",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="liked_commentaries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="лайки",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="liked_publications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="лайки",
            ),
        ),
    ]
