# Generated by Django 5.2.1 on 2025-06-01 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0005_remove_commentary_likes_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentary",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_commentaries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="лайки",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_publications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="лайки",
            ),
        ),
    ]
